sudo: required
language: java
jdk: oraclejdk8
services:
  - docker

script:
  - gradle clean
  - gradle test
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'


notifications:
  email: ramith.gs@gmail.com
    slack: pioneer-ugy5279:VyP1G0w0FfxQR7iFRUOr1ESw
      on_success: always
      on_failure: always