sudo: required
language: java
jdk: oraclejdk8
services:
  - docker

script:
  - ./mvn clean -X

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'


notifications:
  email: ramitha.gs@gmail.com
  slack:
    on_success: always
    on_failure: always